name: Publish Release to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build-release:
    runs-on: ubuntu-latest
    
    environment:
      name: pypi
      url: https://pypi.org/project/polly-kpf/
    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.26"

      - name: Set up Python
        run: uv python install

      - name: Build release distributions
        run: uv build
      
      - name: Publish to PyPI
        run: uv publish
